# Generated by Django 4.1.13 on 2024-09-01 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='number_plate',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bus',
            name='model',
            field=models.CharField(default='Unknown Model', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default='UNKNOWN123', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.CharField(default='End Point Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.CharField(default='Start Point Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_linked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(default='Unknown Driver', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='RestPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_time', models.DateTimeField(default=datetime.datetime.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
        ),
    ]
